const products = [
  {
    name: 'Stripe Royal Blue Suit Set',
    price: '5749.00',
    img: 'https://via.placeholder.com/300',
    category: 'Suits',
    rating: 2,
    _id: '001',
    inStockValue: 10,
    soldStockValue: 5,
    visibility: 'on',
  },
  {
    name: 'Elegant Green Kurta Set',
    price: '4999.00',
    img: 'https://via.placeholder.com/300',
    category: 'Kurtas',
    rating: 4.7,
    productId: '002',
    inStockValue: 8,
    soldStockValue: 12,
    visibility: 'on',
  },
  {
    name: 'Classic Black Sherwani',
    price: '8999.00',
    img: 'https://via.placeholder.com/300',
    category: 'Sherwanis',
    rating: 4.8,
    _id: '003',
    inStockValue: 15,
    soldStockValue: 7,
    visibility: 'on',
  },
  {
    name: 'Royal Embroidered Lehenga',
    price: '12500.00',
    img: 'https://via.placeholder.com/300',
    category: 'Lehengas',
    rating: 4.9,
    productId: '004',
    inStockValue: 5,
    soldStockValue: 3,
    visibility: 'on',
  },
  {
    name: 'Designer Red Saree',
    price: '7999.00',
    img: 'https://via.placeholder.com/300',
    category: 'Sarees',
    rating: 4.6,
    _id: '005',
    inStockValue: 12,
    soldStockValue: 9,
    visibility: 'on',
  },
  {
    name: 'Festive Yellow Anarkali',
    price: '6599.00',
    img: 'https://via.placeholder.com/300',
    category: 'Anarkalis',
    rating: 4.7,
    _id: '006',
    inStockValue: 9,
    soldStockValue: 6,
    visibility: 'on',
  },
  {
    name: 'Pastel Blue Gown',
    price: '10500.00',
    img: 'https://via.placeholder.com/300',
    category: 'Gowns',
    rating: 4.9,
    _id: '007',
    inStockValue: 4,
    soldStockValue: 2,
    visibility: 'on',
  },
  {
    name: 'Traditional Gold Jewelry Set',
    price: '6999.00',
    img: 'https://via.placeholder.com/300',
    category: 'Jewelry',
    rating: 4.8,
    _id: '008',
    inStockValue: 20,
    soldStockValue: 15,
    visibility: 'on',
  },
];

export default products;
